# -*- mode:python -*-

# Copyright (c) 2013 ARM Limited
# All rights reserved.
#
# The license below extends only to copyright in the software and shall
# not be construed as granting a license to any other intellectual
# property including but not limited to intellectual property relating
# to a hardware implementation of the functionality of the software
# licensed hereunder.  You may use the software subject to the license
# terms below provided that you ensure that this notice is replicated
# unmodified and in its entirety in all distributions of the software,
# modified or unmodified, in source code or in binary form.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met: redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer;
# redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution;
# neither the name of the copyright holders nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

import os

Import('env')

thermal = False

# This gem5 tree vendors PIMony in place of the stock DRAMsim3 submodule.
# PIMony provides the gem5::memory::DRAMsim3 SimObject (mem/pimony.*), so when
# it is present we build PIMony INSTEAD of stock DRAMsim3 to avoid a duplicate
# SimObject registration. Both flags are always defined so src/mem/SConscript
# can gate on them without a KeyError on the absent path.
env['HAVE_PIMONY'] = False
env['HAVE_DRAMSIM3'] = False

# See if we got a cloned PIMony repo as a subdirectory.
if os.path.exists(Dir('.').srcnode().abspath + '/PIMony'):
    env['HAVE_PIMONY'] = True
    pimony_path = os.path.join(Dir('#').abspath, 'ext/dramsim3/PIMony/')
    env.Prepend(CPPPATH=Dir('.').srcnode())
    # a little hacky but can get a shared library working
    env.Append(LIBS=['dramsim3', 'gomp'],
                LIBPATH=[pimony_path],     # compile-time lookup
                RPATH=[pimony_path],       # runtime lookup
                CPPPATH=[pimony_path + 'src/'])
    # PIMony is the DRAMsim3 implementation here; do not also build stock
    # DRAMsim3 (same SimObject type -> duplicate registration).
    Return()

# No PIMony: fall through to stock DRAMsim3 if its submodule is present.
if not os.path.exists(Dir('.').srcnode().abspath + '/DRAMsim3'):
    Return()

# We have got the folder, so add the library and build the wrappers
env['HAVE_DRAMSIM3'] = True


dramsim_path = os.path.join(Dir('#').abspath, 'ext/dramsim3/DRAMsim3/')

if thermal:
    superlu_path = os.path.join(dramsim_path, 'ext/SuperLU_MT_3.1/lib')
    env.Prepend(CPPPATH=Dir('.').srcnode())
    env.Append(LIBS=['dramsim3', 'superlu_mt_OPENMP', 'm', 'f77blas',
                      'atlas', 'gomp'],
                LIBPATH=[dramsim_path, superlu_path])
else:
    env.Prepend(CPPPATH=Dir('.').srcnode())
    # a littel hacky but can get a shared library working
    env.Append(LIBS=['dramsim3', 'gomp'],
                LIBPATH=[dramsim_path],  # compile-time lookup
                RPATH=[dramsim_path],  # runtime lookup
                CPPPATH=[dramsim_path+'/src/'])
