#!/bin/sh
cd /home/gem5/spec2017

echo "Reset stats (host may ignore or reset)"
m5 exit

runcpu --size {args.size} --iterations 1 \
        --config myconfig.x86.cfg --define gcc_dir="/usr" \
        --copies {copies}\
        --noreportable --nobuild {args.benchmark} &
BENCH_PID=$!

while kill -0 "$BENCH_PID" 2>/dev/null; do
    m5 exit
    sleep 1
done

wait $BENCH_PID
m5 exit

for filepath in /home/gem5/spec2017/result/*; do
    filename=$(basename $filepath)
    m5 writefile $filepath {output_dir}/$filename
done
m5 exit
